version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - REDIS_URL=redis://:your_redis_password@redis:6379
    # working_dir: /app
    # command: pdm install && pdm run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config=logging.ini
    volumes:
      - ./app:/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis
  frontend:
    build:
      context: ./ticket-dashboard  # Path to the folder containing Dockerfile and React app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://api:8000"  # Ensure this matches your backend service name and port
  redis:
    image: "redis:latest"
    command:
      [
        "redis-server",
        "--requirepass",
        "your_redis_password",
        "--appendonly",
        "yes",
      ]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
