name: Run Pytest

on:
  push:
    branches:
      - main  # Adjust with your default branch if not "main"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Adjust based on your Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies using Poetry
      run: |
        poetry install

    - name: Run tests with pytest
      run: |
        poetry run pytest --cov=./app --cov-report=term --cov-fail-under=70  tests

    - name: Run tests with pytest
      run: |
        poetry run pytest --md-report --md-report-flavor gfm --md-report-output md_report.md

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add md_report.md
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Update pytest results'; git push --set-upstream origin main)
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
